<?php return array (
    'Zend_Acl_AllTests'         => 'Zend/Acl/AllTests.php',
    'Zend_Config_AllTests'      => 'Zend/Config/AllTests.php',
    'Zend_Log_AllTests'         => 'Zend/Log/AllTests.php',
    'Zend_Cache_AllTests'       => 'Zend/Cache/AllTests.php',
    'Zend_Loader_AllTests'      => 'Zend/Loader/AllTests.php',
    'Zend_Locale_AllTests'      => 'Zend/Locale/AllTests.php',
    'Zend_Translate_AllTests'   => 'Zend/Translate/AllTests.php',
    'Zend_Mime_AllTests'        => 'Zend/Mime/AllTests.php',
    'Zend_Mail_AllTests'        => 'Zend/Mail/AllTests.php',
    'Zend_Db_AllTests'          => 'Zend/Db/AllTests.php',
    'Zend_View_AllTests'        => 'Zend/View/AllTests.php',
    'Zend_Paginator_AllTests'   => 'Zend/Paginator/AllTests.php',
    'Zend_Http_AllTests'        => 'Zend/Http/AllTests.php',
    'Zend_Uri_AllTests'         => 'Zend/Uri/AllTests.php',
    'Zend_Controller_AllTests'  => 'Zend/Controller/AllTests.php',
    'Zend_Layout_AllTests'      => 'Zend/Layout/AllTests.php',
    'Zend_Oauth_AllTests'       => 'Zend/Oauth/AllTests.php',
    'Zend_Crypt_AllTests'       => 'Zend/Crypt/AllTests.php',
    'Zend_Auth_AllTests'        => 'Zend/Auth/AllTests.php',
    'Zend_Application_AllTests' => 'Zend/Application/AllTests.php',
    'Zend_Captcha_AllTests'     => 'Zend/Captcha/AllTests.php',
);
